### ISSUE TITLE
How do you calculate reward points of IndusInd Debit card?

### ISSUE THREAD

**Issue by habibmy** [hariks789/cc-transaction-trackers#1]
Some cards variants give 5x Reward Points, some give 6x for offline spends. 
But 
- Platinum
- Platinum Select
- Platinum Exclusive
- Signature
- Signature Select
- Signature Exclusive
- World Select
- World Exclusive
- Plat Premier
- Plat Plus
All these give 6x Reward points for online transactions.

**Comment by hariks789** [comment]
You can use the functions from indus-dc-points.gs
`calculateIndus6XRewardPoints()`
`calculateIndus5XRewardPoints()`

Use these on the google sheets using Extensions>App Script

For now I am only looking for Online Transctions of Visa Signature and Exclusive MC cards specifically

**Comment by habibmy** [comment]
Can you share how are you calculating total monthly spends or how are you converting dates to month and year, like the image you shared on the forum. I am new to spreadsheets.

**Comment by hariks789** [comment]
I modified the original [repo's](https://github.com/TheSidd/EmailExpenseTracker) axis sheet. Sharing a template with some dummy data. I hope it helps

https://docs.google.com/spreadsheets/d/1qyw5R2tqHAjiI_e3iyTMBFyYQil4e64-f9hidluWa8c/edit?usp=sharing

**Comment by habibmy** [comment]
Thank You for sharing.
